### ISSUE TITLE
sessionFactory returns an issue

### ISSUE THREAD

**Issue by joshuacano** [neo4j-examples/sdn4-university#1]
Currently the project won't build currently, right now it returns: 

Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.neo4j.ogm.session.SessionFactory]: Factory method 'getSessionFactory' threw exception; nested exception is java.lang.StringIndexOutOfBoundsException: String index out of range: 1
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)

**Comment by vince-bickers** [comment]
Hi Josh, 

We're unable to reproduce this problem. I would suggest cloning the repo into a new directory, and trying again, in case something went wrong with your initial download. If that still doesn't work, please try the following:

Add a **logback.xml** file into _src/main/resources_, with log-level set to `debug`

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <appender name="console" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d %5p %40.40c:%4L - %m%n</pattern>
        </encoder>
    </appender>
    <root level="debug">
        <appender-ref ref="console" />
    </root>
</configuration>
```

Start the application from the project root, and `tee` the output to a logfile:

`mvn spring-boot:run -X | tee logfile`

You should be able to scan through the logfile to find the problem.

**Comment by 4x0l0tl** [comment]
I think the issue is windows specific and is caused by the following method

``` java
org.neo4j.ogm.metadata.info.DomainInfo.load(String...)
```

specifically 

``` java
String path = packageName.replaceAll("\\.", File.separator);
```

There is a caveat mentioned in javadoc of replaceAll concerning backslashes 

> Note that backslashes () and dollar signs ($) in the replacement string may cause the results to be different than if it were being treated as a literal replacement string; see Matcher.replaceAll. Use java.util.regex.Matcher.quoteReplacement to suppress the special meaning of these characters, if desired.

Since File.separator returns / on unix there is no problem but it will return \ on windows, so the solution would be:

``` java
String path = packageName.replaceAll("\\.", Matcher.quoteReplacement(File.separator));
```

**Comment by maku** [comment]
Yeah, the issues is OS specific. On MacOS it works, on windows I get the error described....
