### ISSUE TITLE
package org.springframework.boot.neo4j does not exist

### ISSUE THREAD

**Issue by zhangweisjz** [neo4j-examples/sdn4-university#13]
Dear, 
I was tying to build this project but maven kept reporting an error " package org.springframework.boot.neo4j does not exist" as you can see from the attachment. I didn't change any pom.xml configuration. May I know how to solve this problem? Thank you very much.

![2016-07-24_18-00-35](https://cloud.githubusercontent.com/assets/4725193/17083177/d3eb0796-51c8-11e6-92a9-f43188b64688.png)

**Comment by luanne** [comment]
Should be fixed with the latest commit #14
