### ISSUE TITLE
Infrastructure for testing

### ISSUE THREAD

**Issue by maku** [neo4j-examples/sdn4-university#2]
I have problems with writing integrations tests based on sdn4-university. 

Would it be possible to enhance the project with basic tests to show how to access neo4j?

**Comment by luanne** [comment]
Please take a look at the tests in the sdn4-cineasts application for now: 
https://github.com/neo4j-examples/sdn4-cineasts/tree/master/src/test/java/org/neo4j/cineasts

**Comment by maku** [comment]
I looked already to sdn4-cineasts with no success
